# Tùy chọn cấu hình cho lệnh 'build'.
- name: Regeneration
  description: Kích hoạt tự động tái tạo trang web khi các tệp được sửa đổi.
  flag: "-w, --[no-]watch"


- name: Configuration
  description: >-
    Chỉ định các tệp cấu hình thay vì sử dụng <code>_config.yml</code> tự động.
    Các cài đặt trong các tệp sau sẽ ghi đè các cài đặt trong các tệp trước đó.
  flag: "--config FILE1[,FILE2,...]"


- name: Plugins
  description: >-
    Chỉ định các thư mục plugin thay vì sử dụng <code>_plugins/</code> tự động.
  option: "plugins_dir: [ DIR1,... ]"
  flag: "-p, --plugins DIR1[,DIR2,...]"


- name: Layouts
  description: >-
    Chỉ định thư mục bố cục thay vì sử dụng <code>_layouts/</code> tự động.
  option: "layouts_dir: DIR"
  flag: --layouts DIR


- name: Drafts
  description: Xử lý và hiển thị các bài đăng nháp.
  option: "show_drafts: BOOL"
  flag: -D, --drafts


- name: Environment
  description: Sử dụng một giá trị môi trường cụ thể trong bản dựng.
  flag: JEKYLL_ENV=production


- name: Future
  description: Xuất bản các bài đăng hoặc tài liệu bộ sưu tập có ngày trong tương lai.
  option: "future: BOOL"
  flag: --future


- name: Unpublished
  description: Hiển thị các bài đăng đã được đánh dấu là chưa xuất bản.
  option: "unpublished: BOOL"
  flag: --unpublished


- name: LSI
  description: >-
    Tạo chỉ mục cho các bài đăng liên quan. Yêu cầu plugin
    <a href="https://jekyll.github.io/classifier-reborn/">classifier-reborn</a>.
  option: "lsi: BOOL"
  flag: --lsi


- name: Limit posts
  description: Giới hạn số lượng bài đăng để phân tích và xuất bản.
  option: "limit_posts: NUM"
  flag: --limit_posts NUM


- name: Force polling
  description: Buộc theo dõi sử dụng polling.
  option: "force_polling: BOOL"
  flag: --force_polling


- name: Verbose output
  description: In đầu ra chi tiết.
  option: "verbose: BOOL"
  flag: -V, --verbose


- name: Silence output
  description: Tắt đầu ra bình thường từ Jekyll trong quá trình xây dựng.
  option: "quiet: BOOL"
  flag: -q, --quiet


- name: Log level
  description: Chỉ định mức độ nhật ký trong số debug, info, warn, hoặc error.
  flag: JEKYLL_LOG_LEVEL=info


- name: Incremental build
  description: >-
    Kích hoạt tính năng thử nghiệm
    <a href="/docs/configuration/incremental-regeneration/">incremental
    build</a> (xây dựng gia tăng). Xây dựng gia tăng chỉ xây dựng lại các bài đăng và trang mà
    đã thay đổi, dẫn đến cải thiện hiệu suất đáng kể cho các trang web lớn,
    nhưng cũng có thể phá vỡ việc tạo trang web trong một số trường hợp nhất định.
  option: "incremental: BOOL"
  flag: -I, --incremental


- name: Disable bundle require
  description: Vô hiệu hóa nhu cầu yêu cầu các gem trong `:jekyll_plugins` Gemfile
  flag: JEKYLL_NO_BUNDLER_REQUIRE=true


- name: Liquid profiler
  description: Tạo hồ sơ hiển thị Liquid để giúp bạn xác định các điểm nghẽn hiệu suất.
  option: "profile: BOOL"
  flag: --profile


- name: Strict front matter
  description: Khiến bản dựng thất bại nếu có lỗi cú pháp YAML trong front matter của trang.
  option: "strict_front_matter: BOOL"
  flag: --strict_front_matter


- name: Web Domain URL
  option: "url: SCHEME://HOST[:PORT]"
  description: >-
    URL chính tắc của thư mục gốc của bản triển khai sản xuất của bạn, bao gồm các thành phần sau:<br>
    &nbsp; &nbsp;• &nbsp; Giao thức (ví dụ: <code>http://</code>)<br>
    &nbsp; &nbsp;• &nbsp; Tên máy chủ hoặc địa chỉ IP (ví dụ: <code>example.org</code>)<br>
    &nbsp; &nbsp;• &nbsp; <em>(Tùy chọn)</em> Số cổng của máy chủ, có tiền tố là dấu hai chấm
    (ví dụ: <code>:8080</code>)<br>
    Giá trị của tùy chọn cấu hình này KHÔNG nên có dấu gạch chéo ở cuối. Nó sẽ được nối thêm
    với <code>baseurl</code> để tạo thành URL đầy đủ đến trang web Jekyll của bạn khi sử dụng
    <a href="/docs/liquid/filters/">bộ lọc Liquid <code>absolute_url</code></a>.<br>
    <strong>LƯU Ý:</strong> Cài đặt này được tự động cấu hình thành <strong>URL localhost</strong>
    khi lệnh <code>jekyll serve</code> được gọi.


- name: Base URL
  description: >-
    Phục vụ trang web từ URL cơ sở đã cho (đường dẫn giữa máy chủ web hoặc gốc tên miền và trang đích của bạn).
  option: "baseurl: /PATH/TO/SITE"
  flag: -b, --baseurl /PATH/TO/SITE


- name: Trace
  description: Hiển thị dấu vết đầy đủ khi xảy ra lỗi.
  flag: -t, --trace
