Tính năng: Build lại tăng dần
  Là một hacker thiếu kiên nhẫn thích viết blog
  Tôi muốn có khả năng tạo một trang web tĩnh
  Mà không phải chờ đợi quá lâu để nó build

  Kịch bản: Tạo ra site đầu ra chính xác
    Giả sử tôi có thư mục _layouts
    Và tôi có thư mục _posts
    Và tôi có các bài viết sau:
      | title    | date       | layout  | content                               |
      | Wargames | 2009-03-27 | default | The only winning move is not to play. |
    Và tôi có layout default chứa nội dung "Post Layout: {{ content }}"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Post Layout: <p>The only winning move is not to play.</p>" trong "_site/2009/03/27/wargames.html"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Post Layout: <p>The only winning move is not to play.</p>" trong "_site/2009/03/27/wargames.html"

  Kịch bản: Tạo file metadata
    Giả sử tôi có file "index.html" chứa nội dung "Basic Site"
    Khi tôi chạy jekyll build -I
    Thì file ".jekyll-metadata" nên tồn tại

  Kịch bản: Build lại khi nội dung được thay đổi
    Giả sử tôi có file "index.html" chứa nội dung "Basic Site"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Basic Site" trong "_site/index.html"
    Khi tôi chờ 1 giây
    Thì tôi có file "index.html" chứa nội dung "Bacon Site"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Bacon Site" trong "_site/index.html"

  Kịch bản: Build lại khi layout được thay đổi
    Giả sử tôi có thư mục _layouts
    Và tôi có trang "index.html" với layout "default" chứa nội dung "Basic Site with Layout"
    Và tôi có layout default chứa nội dung "Page Layout: {{ content }}"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Page Layout: Basic Site with Layout" trong "_site/index.html"
    Khi tôi chờ 1 giây
    Thì tôi có layout default chứa nội dung "Page Layout Changed: {{ content }}"
    Khi tôi chạy jekyll build
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Page Layout Changed: Basic Site with Layout" trong "_site/index.html"

  Kịch bản: Build lại khi một include được thay đổi
    Giả sử tôi có thư mục _includes
    Và tôi có trang "index.html" chứa nội dung "Basic Site with include tag: {% include about.textile %}"
    Và tôi có file "_includes/about.textile" chứa nội dung "Generated by Jekyll"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Basic Site with include tag: Generated by Jekyll" trong "_site/index.html"
    Khi tôi chờ 1 giây
    Thì tôi có file "_includes/about.textile" chứa nội dung "Regenerated by Jekyll"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Basic Site with include tag: Regenerated by Jekyll" trong "_site/index.html"

  Kịch bản: Build lại khi một dependency của document trong collection_dir tùy chỉnh được thay đổi
    Giả sử tôi có thư mục _includes
    Và tôi có file cấu hình với "collections_dir" được đặt thành "collections"
    Và tôi có thư mục collections/_posts
    Và tôi có bài viết sau trong thư mục "collections":
      | title    | date       | layout  | content                                               |
      | Wargames | 2009-03-27 | default | Basic Site with include tag: {% include about.html %} |
    Và tôi có file "_includes/about.html" chứa nội dung "Generated by Jekyll"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Basic Site with include tag: Generated by Jekyll" trong "_site/2009/03/27/wargames.html"
    Khi tôi chờ 1 giây
    Thì tôi có file "_includes/about.html" chứa nội dung "Regenerated by Jekyll"
    Khi tôi chạy jekyll build -I
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Basic Site with include tag: Regenerated by Jekyll" trong "_site/2009/03/27/wargames.html"

  Kịch bản: Một themed-site và tái tạo tăng dần
    Giả sử tôi có file cấu hình với "theme" được đặt thành "test-theme"
    Và tôi có trang "index.md" chứa nội dung "Themed site"
    Khi tôi chạy jekyll build --incremental --verbose
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi nên thấy "Rendering: index.md" trong kết quả build
    Và tôi nên thấy "Themed site" trong "_site/index.html"
    Khi tôi chờ 1 giây
    Và tôi có trang "about.md" chứa nội dung "About Themed site"
    Khi tôi chạy jekyll build --incremental --verbose
    Thì tôi nên nhận được trạng thái thoát bằng không
    Và thư mục _site nên tồn tại
    Và tôi không nên thấy "Rendering: index.md" trong kết quả build
    Nhưng tôi nên thấy "Themed site" trong "_site/index.html"
    Và tôi nên thấy "About Themed site" trong "_site/about.html"
